In [2]:
import pandas as pd 
import numpy as np

In [3]:
"""
receive data from kaggle and convert to csv and save file to data repository 
"""
# !pip install datasets
# from datasets import load_dataset

# # Load the dataset from Hugging Face
# dataset = load_dataset("divaroffical/real_estate_ads")

# # Convert to Pandas DataFrame and save to CSV
# for split in dataset.keys():
#     df = dataset[split].to_pandas()
#     df.to_csv(f"../data/real_estate_ads_{split}.csv", index=False) 
#     print(f"Saved {split} data to real_estate_ads_{split}.csv")


'\nreceive data from kaggle and convert to csv and save file to data repository \n'

In [4]:
df = pd.read_csv(r"../data/real_estate_ads_train.csv")

C:\Users\SAJJAD\AppData\Local\Temp\ipykernel_33864\3362541588.py:1: DtypeWarning: Columns (26,28,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"../data/real_estate_ads_train.csv")


In [5]:
df.head()

cat2_slug       cat3_slug city_slug neighborhood_slug  \
0    temporary-rent           villa     karaj         mehrshahr   
1  residential-sell  apartment-sell    tehran           gholhak   
2  residential-rent  apartment-rent    tehran             tohid   
3   commercial-rent     office-rent    tehran          elahiyeh   
4  residential-sell  apartment-sell   mashhad          emamreza   

      created_at_month    user_type  \
0  2024-08-01 00:00:00  مشاور املاک   
1  2024-05-01 00:00:00  مشاور املاک   
2  2024-10-01 00:00:00          NaN   
3  2024-06-01 00:00:00          NaN   
4  2024-05-01 00:00:00  مشاور املاک   

                                         description  \
0  ۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...   
1  دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...   
2                                    تخلیه پایان ماه   
3  فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...   
4  هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...   

                                              title rent_mode  rent_value  \
0  باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه       NaN         NaN   
1                           ۶۰ متر قلهک فول امکانات       NaN         NaN   
2                          آپارتمان ۳ خوابه ۱۳۲ متر     مقطوع  26000000.0   
3           فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری     مقطوع  95000000.0   
4                  ۱۱۵ متری/شمالی رو به آفتاب/اکبری       NaN         NaN   

   ...  property_type regular_person_capacity extra_person_capacity  \
0  ...            NaN                     4.0                     6   
1  ...            NaN                     NaN                   NaN   
2  ...            NaN                     NaN                   NaN   
3  ...            NaN                     NaN                   NaN   
4  ...            NaN                     NaN                   NaN   

   cost_per_extra_person rent_price_on_regular_days  \
0               350000.0                  1500000.0   
1                    NaN                        NaN   
2                    NaN                        NaN   
3                    NaN                        NaN   
4                    NaN                        NaN   

   rent_price_on_special_days rent_price_at_weekends location_latitude  \
0                3.500000e+09              3500000.0         35.811684   
1                         NaN                    NaN               NaN   
2                         NaN                    NaN         35.703865   
3                         NaN                    NaN               NaN   
4                         NaN                    NaN               NaN   

   location_longitude  location_radius  
0           50.936600            500.0  
1                 NaN            500.0  
2           51.373459              NaN  
3                 NaN              NaN  
4                 NaN              NaN  

[5 rows x 60 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 60 columns):
 #   Column                      Non-Null Count    Dtype  
---  ------                      --------------    -----  
 0   cat2_slug                   1000000 non-null  object 
 1   cat3_slug                   999999 non-null   object 
 2   city_slug                   999998 non-null   object 
 3   neighborhood_slug           437139 non-null   object 
 4   created_at_month            1000000 non-null  object 
 5   user_type                   288882 non-null   object 
 6   description                 1000000 non-null  object 
 7   title                       999946 non-null   object 
 8   rent_mode                   352994 non-null   object 
 9   rent_value                  351322 non-null   float64
 10  rent_to_single              19 non-null       float64
 11  rent_type                   103961 non-null   object 
 12  price_mode                  573606 non-null   object 
 13

In [7]:
# ستون‌های float64
float_columns = df.select_dtypes(include=['float64']).columns

# ستون‌های object
object_columns = df.select_dtypes(include=['object']).columns


In [8]:
"""test for all columns """
print("diff columns" , len(df.columns) - (len(float_columns) + len(object_columns)))


diff columns 0


In [9]:
# df__ = df.isnull().sum().to_frame().reset_index().rename(columns={0: "counts"})
# df__[df__["counts"] > 0]
print("All Columns and Rows" , df.shape)
df.isnull().sum().to_frame().reset_index().rename(columns={0: "counts"}).where(lambda x: x["counts"] > 0).dropna()


All Columns and Rows (1000000, 60)


index    counts
1                    cat3_slug       1.0
2                    city_slug       2.0
3            neighborhood_slug  562861.0
5                    user_type  711118.0
7                        title      54.0
8                    rent_mode  647006.0
9                   rent_value  648678.0
10              rent_to_single  999981.0
11                   rent_type  896039.0
12                  price_mode  426394.0
13                 price_value  431654.0
14                 credit_mode  647006.0
15                credit_value  647905.0
16       rent_credit_transform  647015.0
17         transformable_price  647106.0
18        transformable_credit  647915.0
19          transformed_credit  927591.0
20          transformable_rent  648752.0
21            transformed_rent  927591.0
22                   land_size  813604.0
23               building_size   19606.0
24                   deed_type  746542.0
25           has_business_deed  965321.0
26                       floor  458252.0
27                 rooms_count  154101.0
28          total_floors_count  695648.0
29              unit_per_floor  697717.0
30                 has_balcony  493589.0
31                has_elevator  458251.0
32               has_warehouse  271845.0
33                 has_parking  271844.0
34           construction_year  184172.0
35                  is_rebuilt  470530.0
36                   has_water  966556.0
37     has_warm_water_provider  620500.0
38             has_electricity  966555.0
39                     has_gas  966570.0
40          has_heating_system  631031.0
41          has_cooling_system  649381.0
42                has_restroom  593087.0
43          has_security_guard  968688.0
44                has_barbecue  968802.0
45          building_direction  676077.0
46                    has_pool  970610.0
47                 has_jacuzzi  971272.0
48                   has_sauna  971521.0
49              floor_material  594016.0
50               property_type  972943.0
51     regular_person_capacity  970130.0
52       extra_person_capacity  975991.0
53       cost_per_extra_person  989759.0
54  rent_price_on_regular_days  981932.0
55  rent_price_on_special_days  989537.0
56      rent_price_at_weekends  986449.0
57           location_latitude  344392.0
58          location_longitude  344392.0
59             location_radius  660301.0

In [18]:
df["neighborhood_slug"].nunique()
set(df["neighborhood_slug"])
df.loc[df["neighborhood_slug"].isnull(),"neighborhood_slug"] = "Uncertain"
print(df["neighborhood_slug"].isnull().sum())

0


In [23]:
# handel null values 
set(df["user_type"])
df.loc[df["user_type"].isnull(),"user_type"] = "مشخص نشده"
print(df["user_type"].isnull().sum())


0


In [25]:

# handel null values 
set(df["title"])
df.loc[df["title"].isnull(),"title"] = "مشخص نشده"
print(df["title"].isnull().sum())

0


In [29]:
df[df["cat3_slug"].isnull()]

cat2_slug cat3_slug city_slug neighborhood_slug  \
338801  commercial-rent       NaN   isfahan     khomeinishahr   

           created_at_month user_type  \
338801  2024-07-01 00:00:00      شخصی   

                                              description  \
338801  از بانوان حرفه ای و دارای مشتری دعوت میشود به ...   

                                            title rent_mode  rent_value  ...  \
338801  اجاره صندلی در آکادمی زیبایی ( خمینی شهر)    توافقی         NaN  ...   

        property_type regular_person_capacity extra_person_capacity  \
338801            NaN                     NaN                   NaN   

        cost_per_extra_person rent_price_on_regular_days  \
338801                    NaN                        NaN   

        rent_price_on_special_days rent_price_at_weekends location_latitude  \
338801                         NaN                    NaN         32.692608   

        location_longitude  location_radius  
338801           51.523163              NaN  

[1 rows x 60 columns]

In [46]:
handle_cat_3 = df[(df["cat2_slug"] == 'commercial-rent') & (df["city_slug"] == 'isfahan') & (df["neighborhood_slug"] == 'khomeinishahr' )]
df.loc[df["cat3_slug"].isnull() , "cat3_slug" ] = handle_cat_3["cat3_slug"].mode().values[0]
print(df["cat3_slug"].isnull().sum())

0


In [52]:
df = df.dropna(subset=['city_slug'])

# بررسی اینکه آیا ردیف‌ها درست حذف شدند
print(df['city_slug'].isnull().sum())  # باید 0 چاپ شود

0


In [60]:
df.loc[df["rent_mode"].isnull(), "rent_mode"] = "مشخص نشده"
# بررسی اینکه آیا ردیف‌ها درست حذف شدند
print(df['rent_mode'].isnull().sum())  # باید 0 چاپ شود

0


In [65]:
df[df["rent_value"] == 0 ] # chek for handle null values
df.loc[df["rent_value"].isnull(),"rent_value" ] = -1


In [66]:
# بررسی اینکه آیا ردیف‌ها درست حذف شدند
print(df['city_slug'].isnull().sum())  # باید 0 چاپ شود

0


In [72]:
print(df["rent_to_single"].nunique())
print(df["rent_to_single"].unique())
df.loc[df["rent_to_single"].isnull(),"rent_to_single" ] = -1
print(df["rent_to_single"].unique())

3
[-1.  1.  0.]
[-1.  1.  0.]


In [75]:

print(df["rent_type"].nunique())
print(df["rent_type"].unique())
df.loc[df["rent_type"].isnull(),"rent_type" ] = "unknown"
print(df["rent_type"].unique())

2
[nan 'rent_credit' 'full_credit']
['unknown' 'rent_credit' 'full_credit']


In [80]:
print(df["price_mode"].nunique())
print(df["price_mode"].unique())
df.loc[df["price_mode"].isnull(),"price_mode" ] = "unknown"
print(df["price_mode"].unique())


4
['unknown' 'مقطوع' 'مجانی' 'توافقی']
['unknown' 'مقطوع' 'مجانی' 'توافقی']


In [86]:
print(df["price_value"].nunique())
print(df["price_value"].unique())
df.loc[df["price_value"].isnull(),"price_value" ] = -1
print(df["price_value"].unique())

12943
[           nan 8.50000000e+09 5.75000000e+09 ... 9.71100000e+09
 2.37300000e+09 1.24665822e+08]
[-1.00000000e+00  8.50000000e+09  5.75000000e+09 ...  9.71100000e+09
  2.37300000e+09  1.24665822e+08]


In [89]:
print(df["credit_mode"].nunique())
print(df["credit_mode"].unique())
df.loc[df["credit_mode"].isnull(),"credit_mode" ] = "unknown"
print(df["credit_mode"].unique())

3
[nan 'مقطوع' 'مجانی' 'توافقی']
['unknown' 'مقطوع' 'مجانی' 'توافقی']


In [92]:
print(df["credit_value"].nunique())
print(df["credit_value"].unique())
df.loc[df["credit_value"].isnull(),"credit_value" ] = -1
print(df["credit_value"].unique())

1421
[     nan 7.50e+08 9.50e+08 ... 3.10e+10 3.77e+08 2.68e+08]
[-1.00e+00  7.50e+08  9.50e+08 ...  3.10e+10  3.77e+08  2.68e+08]


In [96]:
print(df["rent_credit_transform"].nunique())
print(df["rent_credit_transform"].unique())
df.loc[df["rent_credit_transform"].isnull(),"rent_credit_transform" ] = "unknown"
print(df["rent_credit_transform"].unique())

2
[nan False True]
['unknown' False True]


In [101]:
print(df["transformable_price"].nunique())
print(df["transformable_price"].unique())
df.loc[df["transformable_price"].isnull(),"transformable_price" ] = "unknown"
print(df["transformable_price"].unique())

2
[nan False True]
['unknown' False True]


In [104]:
print(df["transformable_credit"].nunique())
print(df["transformable_credit"].unique())
df.loc[df["transformable_credit"].isnull(),"transformable_credit" ] = -1
print(df["transformable_credit"].unique())

1420
[     nan 7.50e+08 9.50e+08 ... 3.10e+10 3.77e+08 2.68e+08]
[-1.00e+00  7.50e+08  9.50e+08 ...  3.10e+10  3.77e+08  2.68e+08]


In [115]:
# ستون‌های float64
print('-' * 10, "Float Columns", '-' * 10)
for col in float_columns:
    print(f"Before handling missing values, column '{col}' has {df[col].isnull().sum()} missing values.")
    df.loc[df[col].isnull(), col] = -1
    print(f"After handling, column '{col}' has {df[col].isnull().sum()} missing values.\n")
    print("-" * 30)

# ستون‌های object
print('-' * 10, "Object Columns", '-' * 10)
for col in object_columns:
    print(f"Before handling missing values, column '{col}' has {df[col].isnull().sum()} missing values.")
    df.loc[df[col].isnull(), col] = "Unknown"
    print(f"After handling, column '{col}' has {df[col].isnull().sum()} missing values.\n")
    print("-" * 30)


---------- Float Columns ----------
Before handling missing values, column 'rent_value' has 0 missing values.
After handling, column 'rent_value' has 0 missing values.

------------------------------
Before handling missing values, column 'rent_to_single' has 0 missing values.
After handling, column 'rent_to_single' has 0 missing values.

------------------------------
Before handling missing values, column 'price_value' has 0 missing values.
After handling, column 'price_value' has 0 missing values.

------------------------------
Before handling missing values, column 'credit_value' has 0 missing values.
After handling, column 'credit_value' has 0 missing values.

------------------------------
Before handling missing values, column 'transformable_credit' has 0 missing values.
After handling, column 'transformable_credit' has 0 missing values.

------------------------------
Before handling missing values, column 'transformed_credit' has 0 missing values.
After handling, column 'tran

In [116]:
df.isnull().sum().to_frame().reset_index().rename(columns={0: "counts"}).where(lambda x: x["counts"] > 0).dropna()

Empty DataFrame
Columns: [index, counts]
Index: []

In [118]:
df

cat2_slug         cat3_slug      city_slug neighborhood_slug  \
0         temporary-rent             villa          karaj         mehrshahr   
1       residential-sell    apartment-sell         tehran           gholhak   
2       residential-rent    apartment-rent         tehran             tohid   
3        commercial-rent       office-rent         tehran          elahiyeh   
4       residential-sell    apartment-sell        mashhad          emamreza   
...                  ...               ...            ...               ...   
999995  residential-sell    apartment-sell     kermanshah         Uncertain   
999996  residential-rent    apartment-rent         tehran             darya   
999997  residential-sell  house-villa-sell           yazd         Uncertain   
999998    temporary-rent   suite-apartment  bandar-anzali         Uncertain   
999999  residential-rent    apartment-rent         tehran           jeyhoun   

           created_at_month    user_type  \
0       2024-08-01 00:00:00  مشاور املاک   
1       2024-05-01 00:00:00  مشاور املاک   
2       2024-10-01 00:00:00    مشخص نشده   
3       2024-06-01 00:00:00    مشخص نشده   
4       2024-05-01 00:00:00  مشاور املاک   
...                     ...          ...   
999995  2024-07-01 00:00:00  مشاور املاک   
999996  2024-07-01 00:00:00  مشاور املاک   
999997  2024-11-01 00:00:00    مشخص نشده   
999998  2024-09-01 00:00:00    مشخص نشده   
999999  2024-08-01 00:00:00  مشاور املاک   

                                              description  \
0       ۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...   
1       دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...   
2                                         تخلیه پایان ماه   
3       فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...   
4       هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...   
...                                                   ...   
999995  ~~~مشاورین املاک قبادی~~~\n■جنوبی تک واحدی\n■د...   
999996  نوساز     \n\n تک واحدی\n\nشخصی  ساز\n\nروف گا...   
999997  سلام ودرود\nفروش منزل مسکونی واقع در خیابان ان...   
999998  سویت بدون خواب (روبه دریا و معمولی)\nسویت ۱خوا...   
999999  ⚜️املاک بزرگ میلیارد⚜️\n✅️۴۰ متر یک خواب\n✅️نو...   

                                                    title  rent_mode  \
0        باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه  مشخص نشده   
1                                 ۶۰ متر قلهک فول امکانات  مشخص نشده   
2                                آپارتمان ۳ خوابه ۱۳۲ متر      مقطوع   
3                 فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری      مقطوع   
4                        ۱۱۵ متری/شمالی رو به آفتاب/اکبری  مشخص نشده   
...                                                   ...        ...   
999995                        آپارتمان ۱۸۰ متری وحدت غربی  مشخص نشده   
999996       آپارتمان  ۱۱۰  متری     سعادت   آباد    دریا      مقطوع   
999997  منزل فروشی.  خیابان انقلاب   نرسیده به کارخانه...  مشخص نشده   
999998                    مجتمع ویلایی کنار ساحل پاسداران  مشخص نشده   
999999                       ۴۰ متر/ یک خواب /فول بازسازی      مجانی   

        rent_value  ...  property_type regular_person_capacity  \
0             -1.0  ...        Unknown                     4.0   
1             -1.0  ...        Unknown                    -1.0   
2       26000000.0  ...        Unknown                    -1.0   
3       95000000.0  ...        Unknown                    -1.0   
4             -1.0  ...        Unknown                    -1.0   
...            ...  ...            ...                     ...   
999995        -1.0  ...        Unknown                    -1.0   
999996  45000000.0  ...        Unknown                    -1.0   
999997        -1.0  ...        Unknown                    -1.0   
999998        -1.0  ...        Unknown                     5.0   
999999         0.0  ...        Unknown                    -1.0   

       extra_person_capacity  cost_per_extra_person  \
0                          6               350000.0   
1                    Unknown        